version: '3.4'
volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "MyOrdersDb"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    container_name: mydatabase

  myorders.web.api:
    image: myorderswebapi
    build:
      context: .
      dockerfile: MyOrders/MyOrders.Web.Api/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Docker
       - ConnectionStrings__MyOrdersContext=Host=host.docker.internal;Port=5432;Database=MyOrdersDb;User Id=postgres;Password=password;Timeout=15;
    container_name: myorders
    ports:
      - "5500:80"

  proxyserver:
    image: nginx:1.22.0
    volumes:
        - ./Nginx/proxy:/etc/nginx/conf.d/
        - ./Nginx/proxy/nginx.conf:/etc/nginx/nginx.conf
    container_name: proxy
    ports:
        - "80:80"
